kind: Service
apiVersion: v1
metadata:
  name: stupidchess-web-service
spec:
  selector:
    role: web-service

  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
