kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: stupidchess-admin
  namespace: stupidchess
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - services
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    nonResourceURLs: []
  - apiGroups:
      - extensions
    resources:
      - deployments
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    nonResourceURLs: []
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - role-bindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    nonResourceURLs: []
