kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: stupidchess-readonly
  namespace: stupidchess
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
    nonResourceURLs: []
  - apiGroups:
      - extensions
    resources:
      - deployments
      - ingresses
    verbs:
      - get
      - list
      - watch
    nonResourceURLs: []
