version: '2'
services:
  nginx:
    image: stupidchess-nginx:0.0.0-dev
    entrypoint: 'nginx -c /etc/nginx/local/nginx.conf -g "daemon off;"'
    volumes:
      - '../etc/nginx:/etc/nginx/local'
    volumes_from:
      - webpack_builder
      - uwsgi
    ports:
      - '80:80'
  server_code:
    image: stupidchess-server_code:0.0.0-dev
  uwsgi:
    image: stupidchess-uwsgi:0.0.0-dev
    entrypoint: 'uwsgi --ini /etc/uwsgi/uwsgi.ini:local'
    volumes:
      - '../server:/var/lib/johnmalcolmnorwood/stupidchess/server'
      - '../etc/uwsgi:/etc/uwsgi'
    volumes_from:
      - server_code
  webpack_builder:
    image: stupidchess-webpack_builder:0.0.0-dev
    volumes:
      - '../web/src:/var/lib/johnmalcolmnorwood/stupidchess/src'
    entrypoint: 'webpack --watch'
