environment: !EnvVar {name: "JCONFIGURE_ACTIVE_PROFILES", default: "none"}

endpoint_prefixes:
  healthcheck: /health
  auth: /api/user
  game: /api/game
  record: /api/record

MONGODB_SETTINGS:
  db: stupidchess
  host: mongo
