kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stupidchess-mongo-pv-claim
  namespace: stupidchess
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: stupidchess
