version: '2'
services:
  mongo:
    image: mongo:2.6.4
    ports:
      - 27017:27017

  nginx:
    image: stupidchess-nginx:current
    entrypoint:
      - nginx
      - -c
      - /etc/nginx/local/nginx.conf
      - -g
      - daemon off;
    volumes:
      - ../../etc/nginx:/etc/nginx/local
    volumes_from:
      - uwsgi
    ports:
      - 80:80

  uwsgi:
    image: stupidchess-uwsgi:current
    links:
      - mongo
    entrypoint: uwsgi --ini /etc/uwsgi/uwsgi.ini:local
    volumes:
      - ../../server/packages:/var/lib/johnmalcolmnorwood/stupidchess/server:ro
      - ../../etc/uwsgi:/etc/uwsgi:ro
