kind: PersistentVolume
apiVersion: v1
metadata:
  name: stupidchess-mongo-pv
  labels:
    app: stupidchess
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/stupidchess
    server: rp3-smi-kbw-nfs-000
