version: "2"
services:
  mongo:
    image: dhermanns/rpi-mongo:2.6.4
    ports:
      - 27017:27017

  nginx:
    image: stupidchess-rpi_nginx:current
    entrypoint:
      - nginx
      - -c
      - /etc/nginx/local/nginx.conf
      - -g
      - daemon off;
    volumes:
      - ../../etc/nginx:/etc/nginx/local:ro
    volumes_from:
      - uwsgi
    ports:
      - 80:80

  uwsgi:
    image: stupidchess-rpi_uwsgi:current
    links:
      - mongo
    entrypoint: uwsgi --ini /etc/uwsgi/uwsgi.ini:local
    volumes:
      - ../../server/packages/stupidchess/src:/var/lib/johnmalcolmnorwood/stupidchess/server/src:ro
      - ../../etc/uwsgi:/etc/uwsgi:ro
